apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: testapp
  namespace: testapp
spec:
  selector:
    matchLabels:
      app: web-systeminfo
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: web-systeminfo
    spec:
      containers:
      - name: webserver
        image: marty808/web-systeminfo:0.4
        ports:
        - containerPort: 80
---
kind: Service
apiVersion: v1
metadata:
  name: testapp-service
  namespace: testapp
spec:
  selector:
    app: web-systeminfo
  ports:
    - protocol: TCP
      port: 80
      name: web

