apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: testapp
  namespace: testapp
spec:
  selector:
    matchLabels:
      app: nginx
#  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
---
kind: Service
apiVersion: v1
metadata:
  name: testapp-service
  namespace: testapp
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      name: web

